#!/bin/bash
# Author: Paulo Jeronimo (email: paulojeronimo@gmail.com, twitter: @paulojeronimo)
set +x

BASEDIR=/vagrant
source "$BASEDIR"/config || exit 1
source "$BASEDIR"/defaults || exit 1

sudo tar cvfP "/$BACKUP_DIR/$VAGRANT_BACKUP_TAR" /var/cache

# vim: set ts=4 sw=4 expandtab:
